### ISSUE TITLE
Union style

### ISSUE THREAD

**Issue by warpfork** [ipfs/ipld-unixfs#20]
We should talk about the way we do "unions" (a.k.a. "sum types", if you prefer that term).

We have a Union field for {file|dir|symlink|...} in Unixfs, so this is an important choice in our design.

### options

There are least three different ways that Unions are seen serialized in a format like json.

- Envelope style: `{"type":"$TYPEHINT", "msg":$CONTENT}` -- the content is a nested object, so the type hint can be clearly found.  Every union object is a two-field map.
- Keyed style: `{"$TYPEHINT": $CONTENT}` -- the content is a nested object, and it's in the key that *is* the type hint.  Every union object is a *one*-field map.
- Inline style: `{"type":"$TYPEHINT", $CONTENT}` -- the type hint is a sibling of all the other content fields.  The union object is an $N-field map.
- (Arguably, a fourth style; eschewing a type hint at all and going full-on "duck typing".  But let's not talk about that; it makes by *far* the most work for implementors; and all of its traits and drawbacks are almost identical to Inline-style anyway, just with more bonus ambiguity.)

### review of the options

- **Envelope style**
  - is fairly popular because it comes to mind easily.
  - it works: there's no limit to the range of valid content values.
  - unions take up two layers of object; one for the envelop, one for the content.
  - implementation: in golang, this is `struct{ Type string, Msg interface{} }`.
    - a custom unmarshal method is needed (small amount of boilerplate, but liveable)
    - *the content ends up getting parsed twice*.  Necessary because the full parse happens once and gives you known-to-be-json but-still-not-mapped-into-a-struct bytes; and then your unmarshal method picks what type of struct to use for the content based on the type string, and parses *again*.  Significantly inefficient.
- **Keyed style**
  - it works: there's no limit to the range of valid content values.
  - unions take up two layers of object; one for the envelop, one for the content.
  - implementation: in golang, this is `struct { Foo *foo, Bar *bar }` plus separate structs for types `foo` and `bar`.
    - commonly seen.  Kubernetes APIs use this pattern in *spades*.
    - doesn't need a custom unmarshal method (nice) but does require a boilerplatey switch statement for which of the fields is non-null (and this method must be careful to do something well-defined if there are multiple fields defined, which is invalid for a Union).
    - single pass finishes all decoding (contrast with envelope-style), so this is reasonably efficient.
  - implementation: in golang *with refmt*, `type YourUnion interface{ _unionMarker() }`.
    - only a single value can be stored (fixes the issue in the other golang implementation pattern where you have to write the logic for checking for more than one non-nil field yourself, as well as making it impossible to accidentally construct invalid values in your program).
    - [build-in concept with explicit configuration](https://github.com/polydawn/refmt/pull/30): `KeyedUnion().Of(map[string]*AtlasEntry{"foo": ..., "bar": ...})`
    - incorrect presence of more than one field is consistently reported as an error from the deserializing step.
    - with extremely efficient implementation: since it's *known* to be a single value map, we never have to buffer anything internally nor backtrack.
- **Inline style**:
  - can always be glued onto an existing protocol in an ad hoc way (which may be error prone...)
  - *is not safe for all content* because your content can't contain the same key as the magic "type" hint keyword.
  - unions only take up one layer of object.
  - implementation: in golang: this is pure nastiness.
    - it would look a bit like the Envelope-style code in that there'd be an `interface{}`, but it wouldn't even be obvious where to put the custom unmarshaller method that you'd need (it would have to be on every object that *contains* a union field?!).
    - like the Envelope-style code: content requires parsing *at least twice*.  The first parse would target a `struct { Type string }` dummy object (and ignore all data that doesn't match that field), and a second parse would target a correct type.  Significantly inefficient.

A couple meta notes on these observations: 

1. "there's no limit to the range of valid content values" and "unions take up two layers of object" always go hand-in-hand.  One could argue that two layers of object are unsightly, but it seems to be a necessary price to pay.
2. I'm only commenting on implementations in golang; mea culpa.  I suspect a lot of this seems less impactful from a language like javascript because it can just always deserialize things into maps and apply type-like behaviors later; not so in golang (or more generally in any languages with struct memory layout opinions).

### recommendation

Keyed-style Unions.  They're both Correct for all content, and can be implemented more efficiently.

### next steps

The spec as currently drafted is using envelope-style (or possibly a hybrid of envelope style and inline style, since we've got 'data' which is variable content type and 'size' which is also on what I'd otherwise call the envelope).

If Keyed-style Unions seem acceptable to everyone, let's switch over ASAP.  I'm not sure if it will be more typing to do it immediately or do it right after merging our two open PRs.

**Comment by Stebalien** [comment]
Let's *not* make protocol design decisions because of how go does enums. Kubernetes probably uses them because it uses golang. Almost every other API I've seen has using inline or envelop because they play well with dynamic languages (and you can't end up with weird objects with multiple types).

Note: We're really dealing with dynamic types here, not "unions". That is, the set of types is open.

**Comment by warpfork** [comment]
The performance implications of the approaches are language agnostic.  Keyed-union is always efficiently parsible because you always learn what to do with the content before you reach the content.  If you use the envelope approach, the kind hint might *come second* in the map, causing you to need to buffer the entirety of all the deeper content before you can handle it.

(This is one of those things I never would've thought about before writing refmt, but now it's a "cannot unsee" thing.  That potential need to buffer an unbounded number of tokens before you can make sense of them makes a very ugly implementation and very nasty implications for performance.  And then imagine if you've got nested unions...)

**Comment by mikeal** [comment]
I have a few questions about how we expect implementations to consume this information.

1. If an implementation has no support for anything in the union field, what is the expected outcome if a union field is present? Fail, warn, ignore?
2. If an implementation has support for specific kinds of union field information, what is the expected outcome when there is a kind they do no support? Fail, warn, ignore?

If for all of these the expected outcome is to ignore then I think we should push the union filed + kind to the top level:

```
{ type: 'file'
  `union-${kind}`: msg
  ...
}
```

But if we think that implementations that support certain types of unions should fail on others we should do:

```
{ type: 'file'
  union: { kind, msg }
}
```

**Comment by Stebalien** [comment]
> The performance implications of the approaches are language agnostic. Keyed-union is always efficiently parsible because you always learn what to do with the content before you reach the content. If you use the envelope approach, the kind hint might come second in the map, causing you to need to buffer the entirety of all the deeper content before you can handle it.

Sort of. Yes, you may have to scan through the content, but at least with the *envelope* approach, you should be able to skip through it pretty quickly (without having to deserialize anything yet). This situation can also be improved by using something like `@type` and requiring the "canonical" encoding (although that's not perfect).

But yeah, we'd need to support (a) scanning for specific fields and (b) buffering the entire block in memory.

---

@mikeal 

@warpfork is using "kind" *instead* of "type". He's suggesting `{"file": { "data" : .... } }` instead of `{"type": "file", "data": ... } `

**Comment by mikeal** [comment]
I see, I misunderstood the original ask.

The problem I see with keyed style is that it leaves open the possibility of creating a single entity that has both types and, I think, we want to explicitly prevent this.

**Comment by warpfork** [comment]
> If an implementation has support for specific kinds of union field information, what is the expected outcome when there is a type/kind keyword they do not support? Fail, warn, ignore?

Those are good questions, and I agree we should have some suggestions for how those situations are handled and document them.  

What's correct to do with an unrecognized value in a union (or similarly an enum) might vary by situation.  I think usually the default behavior of a library which has some understandings of union patterns should be to raise an error for unknown values of the type hint field... but I'd if I was implementing such a library, I'd also engineer it to take callbacks of some kind which can define other behaviors.  So for example for Unixfsv2, perhaps we'd say that for unknown node types, we'll emit a warning and continue instead (much like we've also discussed regarding what to do with e.g. trying to manifest symlinks on a system that doesn't support them: make this a configurable behavior).

Long story short: I think we can punt on some of this and further refine those details later.

> This situation can also be improved by using something like @type and requiring the "canonical" encoding (although that's not perfect).

That's true.  Doing the envelope form and choosing a keyword for the type hint that's going to alphasort before the key for the content *and requiring* canonical order will result in objects which can be one-pass decoded.

It's a, um, interesting requirement though.  In IPLD in general, we're accepting non-canonically ordered objects and parsing them and at most indicating warnings for noncanonical orderings, right?  So unless we get stricter about that, we'll still have to implement code to handle all the issues of the less easy ordering.

> skip through it pretty quickly (without having to deserialize anything yet)

*Relatively*.  That still tends to be pretty nontrivial.  It might be better so say that you still have to *deserialize*, you just don't have to (or rather, can't) *unmarshal* yet.  In JSON, you have to run the full-on parser for every single byte (there's no way to skip a string without parsing it an all its potential escaping, right?)... and then you can choose between storing tokens (big), storing all the bytes for a second re-parse later (big *and* slow), or storing a list of offsets (doable, but complicated code, and you're still storing all the bytes).  In CBOR, you can skip over some decent amount of stuff like string bodies, but you still have to traverse the entirety of all the object trees (length in maps and arrays is an element count, not a foreknowledge of how many *bytes* of content in total that structure has)... and then you still have the same three none-of-them-great choices as with JSON for keeping any of what you've learned.

> @warpfork is using "kind" instead of "type". 

Hrm, yeah, that word may have been more confusing than not.  I'll go edit the first post; I think it'll be less confusing with the word "type" in most places.

**Comment by warpfork** [comment]
> The problem I see with keyed style is that it leaves open the possibility of creating a single entity that has both types and, I think, we want to explicitly prevent this.

Yeah, that's a good point.  I don't know what to do about it other than check that and reject it.

If we were sitting here with some kind of a schema system, and it had `type Foo union keyed = Bar | Baz | Etc`, I'd want my library that understands this schema to do this kind of check for me, just like I'd want it to check that the type keyword is one of a known set for any of the patterns of union serialization.

I think this isn't actually a huge issue though, because we have the same category of ambiguities with the other styles of union serialization -- for example, what do if we expect an envelope-style union with keywords "type" and "msg" and then someone goes and puts a third key-value pair in it under "combo-b-b-b-breaker"?  Since that can certainly be *done* in serial data authored outside of our system, we need a defined error handling path for that as well.

**Comment by rvagg** [comment]
I've had to do more than my fair share of converting data from XML to JSON and by far the most common approach by library authors that deal with that challenge is using envelopes. A lot of that is about safety and the downsizing in resolution and data expressiveness when you go from XML to JSON. If you want to do more than just read pieces of data, say convert it to something more useful, you end up having to extract and flatten into something that feels more native.

It's that _native feeling_ that would recommend the inline style but of course you then get into trouble if your type is under the property `"type"` but it's also a property of your data (which is why you see things like `"$"` in conversion libraries ... _find a key that's least likely to be used and cross your fingers_). This is a bit too reminiscent of JavaScript prototype dangers (`"toString"`, `"valueOf"`).

The keyed style is cleaner than the envelope but you still have that extra layer. You also lose most of the inheritance/shape-sharing benefits of union data. If you have a bunch of objects that are either directories or files but all you cared about was an `owner` property, you couldn't do a generic lookup with a keyed union. `obj.owner` (or `obj.msg.owner` for envelope) vs `(obj.dir || obj.file).owner`. `shape.height` vs `(shape.square || shape.rectangle || shape.triangle || shape. .....).height`.

Envelopes add ugly layers and are essentially a leaky abstraction but they're safe and predictable and there's a good reason it ends up being the de facto approach for converting between data formats with different levels of expressiveness. js-ipld already uses this pattern to wrap IPLD nodes it returns from fetches (`node.value.whatever` right?) so it's not unfamiliar.

**Comment by Kubuxu** [comment]
One other reference here might be Protobuf's `oneof` functionality. It is closest to keyed style but also similar to envelope style as each union member has a unique tag that is stored before the content.

**Comment by Gozala** [comment]
Please consider how choice of treating unions here affects flow / typescript users. Envelope style from the list works best with the type checkers allowing them to refine type of the tagged data, keyed style is not supported at all by either, and inline style sort of works but is prone to errors (if multiple keys match across the variants at least flow gets confused and can't decide which one is a tag).

With this context I would highly recommend going with envelope style.

**Comment by rvagg** [comment]
closing for archival
