### ISSUE TITLE
Add a "metadata" field.

### ISSUE THREAD

**Issue by Stebalien** [ipfs/ipld-unixfs#22]
All files/directories should support metadata so this should be safe as a common field.

**Comment by mikeal** [comment]
There seemed to be some disagreement in prior threads as to what should go in the “metadata” field and what should not. Is there a reason we shouldn’t just push metadata into the unclaimed top level fields?

**Comment by Stebalien** [comment]
Not really. I mean, my primary worry is that we may want to add a new "reserved" top-level field but, really, that's probably not an issue (we're going to be doing never-ending duck-typing anyways).
