### ISSUE TITLE
How many file data layouts do we need in UnixFSv2?

### ISSUE THREAD

**Issue by mikeal** [ipfs/ipld-unixfs#32]
In UnixFSv1 we have the “balanced dag” and the “trickle dag.”

In UnixFSv2 we have a lot of flexibility that can help us define more of these the future, so the initial layout we choose can be updated later a bit easier than we can in UnixFSv1.

We also expect Graphsync to be integrated into IPFS at some point, which changes some of the constraints that made trickle dag so attractive.

My preference would be to design one good layout that handles the majority of our concerns and land it as part of UnixFSv2, without implementing any alternative layouts until a future date.

We’ve also been having an interesting conversation about [in-place edits](https://github.com/ipfs/unixfs-v2/issues/30). We should take this use case in to account when designing the layout of UnixFSv2 data and not use a layout that can only be re-constructed by another full serialization of the layout.

**Comment by mikeal** [comment]
I’ve written a spec, schema and implementation of a new data layout https://github.com/ipld/specs/pull/211

**Comment by rvagg** [comment]
closing for archival
