### ISSUE TITLE
Transfer to IPLD org

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipld-unixfs#35]
@mikeal may I?

**Comment by mikeal** [comment]
sure, we will probably archive it since the work is happening in the specs repo :)

**Comment by hsanjuan** [comment]
SGTM. Thanks! Transfer incoming

**Comment by hsanjuan** [comment]
Bah I don't have perms on IPLD to create repositories, thus cannot transfer. Can you help @mikeal ?

**Comment by mikeal** [comment]
done :)
