### ISSUE TITLE
Move to ipld org

### ISSUE THREAD

**Issue by ghost** [ipfs/ipld-unixfs#5]

**Comment by daviddias** [comment]
Doesn't need to. Same as unixfs-engine, ipld-unixfs (which should have a batter name because the previous unixfs is also IPLD) is just a new version of unixfs that uses dag-cbor.

See comment here https://github.com/ipfs/ipld-unixfs/pull/2#discussion_r151418121

**Comment by ghost** [comment]
Fiiine :) 👍
