### ISSUE TITLE
Record the FileSize in directories as well

### ISSUE THREAD

**Issue by Stebalien** [ipfs/ipld-unixfs#7]
Currently, sharded directories don't record the filesize (size of the directory) in the root. To be consistent with unix, we should do this.

**Comment by warpfork** [comment]
I question this.

[An earlier comment in Issue#1](https://github.com/ipfs/ipld-unixfs/issues/1#issuecomment-335254386) points out that the definition of "size" in directories has not been used consistently, historically.

I'd also consider that directory entry length info would make [Issue#6 (seeking in dirs)](https://github.com/ipfs/ipld-unixfs/issues/6) interesting: any changes in entries would require republishing the root node.  If we need iterables/pagination in IPLD in general... maybe this entry length info question should be put into that discussion?

**Comment by Stebalien** [comment]
> any changes in entries would require republishing the root node.

We already need to do that as shareded directories are merkle trees.

> An earlier comment in Issue#1 points out that the definition of "size" in directories has not been used consistently, historically.

I agree, I'd just like to be consistent. An alternative is to just get rid of directory sizes.

**Comment by warpfork** [comment]
> We already need to do that as shareded directories are merkle trees.

... ow, right, I have no idea what I was thinking.  I think some neuron reminiscing about atime propagation misfired there for basically no reason.

> we need iterables/pagination in IPLD in general

I'm still cooking on this thought.  Dirs seem like an instance of iterables.  My feeble google/ddg-fu hasn't turned up any good links for "IPLD pagination" or "IPLD iterable" yet though.  Maybe I'll make an issue in a bit if I still can't find any.

**Comment by kevina** [comment]
I am thinking we should just not use file size for directives and instead include the more useful count of the number of entries.  See #9.

**Comment by rvagg** [comment]
closing for archival
